apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin4-data
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
  storageClassName: longhorn  # Use your storage class