apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-internal-tls
  namespace: harbor
spec:
  secretName: harbor-internal-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: core.harbor.svc.cluster.local
  dnsNames:
  # Full FQDNs
  - core.harbor.svc.cluster.local
  - registry.harbor.svc.cluster.local
  - portal.harbor.svc.cluster.local
  - jobservice.harbor.svc.cluster.local
  - trivy.harbor.svc.cluster.local
  
  # Bare hostnames (for in-namespace communication)
  - harbor-core
  - harbor-registry
  - harbor-portal
  - harbor-jobservice
  - harbor-trivy
  duration: 8760h
  renewBefore: 720h
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth