repositories:
- name: cilium
  url: https://helm.cilium.io/
releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.17.5
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml
