repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: mimir
  namespace: grafana-mimir
  createNamespace: true
  chart: grafana/mimir-distributed
  version: ~5.8.0
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml
