releases:
- name: crunchy-postgres-operator
  namespace: crunchy-postgres-operator
  chart: oci://registry.developers.crunchydata.com/crunchydata/pgo
  version: "5.6.0" # Specify version or use latest
  createNamespace: true
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml
