repositories:
- name: jetstack
  url: https://charts.jetstack.io/

releases:
- name: trust-manager
  namespace: cert-manager
  createNamespace: false
  chart: jetstack/trust-manager
  version: v0.20.2
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml