repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana-loki
  namespace: grafana-loki
  createNamespace: true
  chart: grafana/loki
  version: ~6.42.0
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml
