apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-access-keys
  namespace: harbor
spec:
  # Reference to VaultConnection (uses default if not specified)
  vaultAuthRef: harbor-app

  # Path to secret in Vault
  mount: secret
  type: kv-v2
  path: s3/minio/access-keys/harbor

  # Kubernetes secret to create/update
  destination:
    name: minio-access-keys
    create: true
    type: Opaque
  
  # Refresh the secret every 5 minutes
  refreshAfter: 5m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-configuration
  namespace: harbor
spec:
  vaultAuthRef: harbor-app
  mount: secret
  type: kv-v2
  path: registry/harbor/app/configuration

  # Kubernetes secret to create/update
  destination:
    name: harbor-configuration
    create: true
    type: Opaque
  
  # Refresh the secret every 5 minutes
  refreshAfter: 5m