apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: default
  namespace: core-api
spec:
  # Address of your Vault server
  address: "http://vault.vault.svc.cluster.local:8200"
  # Skip TLS verification (set to true if using HTTP or self-signed certs)
  skipTLSVerify: true