apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: core-api-postgres
  namespace: core-api
spec:
  # Reference to the VaultConnection in the same namespace
  vaultConnectionRef: default

  # Kubernetes authentication method
  method: kubernetes
  mount: kubernetes

  kubernetes:
    # Role configured in Vault for core-api-postgres
    role: "core-api-postgres"

    # Service account core-api-postgres uses
    serviceAccount: "postgres"