apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-mimir-app
  namespace: grafana-mimir
spec:
  # Reference to VaultConnection (uses default if not specified)
  vaultAuthRef: mimir
  
  # Path to secret in Vault
  mount: secret
  type: kv-v2
  path: grafana-mimir/app/configuration
  
  # Kubernetes secret to create/update
  destination:
    name: grafana-mimir-app
    create: true
    type: Opaque
  
  # Refresh the secret every 5 minutes
  refreshAfter: 5m
  
  # Rollout restart deployments when secret changes
    # rolloutRestartTargets:
    #   - kind: Deployment
    #     name: mimir