repositories:
- name: minio-operator
  url: https://operator.min.io

releases:
- name: minio
  namespace: minio-operator
  createNamespace: true
  chart: minio-operator/operator
  version: 7.1.1
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml