repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: grafana
  createNamespace: true
  chart: grafana/grafana
  version: 10.0.0
  values:
  - values/{{ .Values.environment | default .Environment.Name }}.yaml
